language: node_js

node_js:
  - 8
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8 STORAGE_DRIVER=diskfs
  - CXX=g++-4.8 STORAGE_DRIVER=gridfs

matrix:
  fast_finish: true

services:
  - mongodb
  - postgresql

before_script:
  - cp config.js.example.${STORAGE_DRIVER} config.js
