language: node_js

node_js:
  - "6"
  - "7"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8

services:
  - mongodb

before_script:
  - cp config.js.example config.js
